### ISSUE TITLE
Bug- Select Credential

### ISSUE THREAD

**Issue by divyakalraness** [NessDigitalEngineering/salesforce-practice-studio#131]
As a practice manager I should only be able to search those credentials which are not assigned or Earned. 

Log in Demo Org 
1. Search Divya Kalra user
2. Go to Select Credential Component.
3. Search User experience Designer credential

AC: I should not get "User experience Designer" credential in my search result as it is already earned.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/104009274/193030987-fa9b5b3e-2ae9-4b2f-b094-f76a7dea795b.png">

**Comment by nitinsavanurness** [comment]
@divyakalraness  - pls retest, should be fixed

**Comment by divyakalraness** [comment]
@nitinsavanurness Tested and Closed.
