### ISSUE TITLE
Credential Assignment 

### ISSUE THREAD

**Issue by divyakalraness** [NessDigitalEngineering/salesforce-practice-studio#29]
As a practice Manager, when I login to PBO, On my Home screen I should be able to perform the below:
1. Search for  available credentials 
2. View Recommended credentials 
3. Search for Active Practice Members to assign credentials
4. View Earned credentials for selected Practice Member

AC:
1. Given I am a practice Manager when I go to my home screen, I should be able to search for Active Practice Members from the Select User Section.
2. Given I am a Practice Manager I should be able to search the available Credentials in Select Credentials Section and suggestions should be populated based on the letters typed in a search bar.
3. Given I am a Practice Manager I should also be able to view the Earned Credentials on the Earned Credentials Component.
4. Given I am a Practice Manager my search results should only show  those credentials that are not earned by the Practice Member in the past. 
5. Given I am a Practice Manager I should be able to see Recommended Credentials (based on the Navigator Expertise set by the Practice Member) on the Recommended Credentials Component and accordingly select the same from the Recommended Credentials component. 
6. Given I am a Practice Manager I should be able to see Show More on my Earned and Recommended Credentials and clicking on Show More should reflect the list.

**Comment by divyakalraness** [comment]
[
[Cred Assignment- Requirement 1.pdf](https://github.com/NessDigitalEngineering/salesforce-practice-studio/files/8531488/Cred.Assignment-.Requirement.1.pdf)
](url)

**Comment by divyakalraness** [comment]
[Assign Credentials Diagram.pptx](https://github.com/NessDigitalEngineering/salesforce-practice-studio/files/8534864/Assign.Credentials.Diagram.pptx)

**Comment by divyakalraness** [comment]
![Uploading image.png…]()

**Comment by divyakalraness** [comment]
[Assign Credentials Diagram.pptx](https://github.com/NessDigitalEngineering/salesforce-practice-studio/files/8534943/Assign.Credentials.Diagram.pptx)

**Comment by divyakalraness** [comment]
![image](https://user-images.githubusercontent.com/104009274/164549421-2e76186e-558c-4729-bf95-01dcd8f293bd.png)

**Comment by divyakalraness** [comment]
<img width="455" alt="Cred Assignment- Requirement 1" src="https://user-images.githubusercontent.com/104009274/164549658-c57b2660-88ce-4a33-908f-7c0c29b44028.png">

**Comment by divyakalraness** [comment]
![Credential Assignment](https://user-images.githubusercontent.com/104009274/164793759-0a4fcf2f-87df-4a22-8560-366918eb3ad0.png)

**Comment by divyakalraness** [comment]
![Credential Assignment](https://user-images.githubusercontent.com/104009274/164802086-b8b48366-8b7c-418e-b000-9c47c4f35a97.png)

**Comment by vidhyabalasubramaniamness** [comment]
I am taking up the first AC: Given I am a practice Manager when I go to my home screen, I should be able to search for Active Practice Members from the Assign User Section.

**Comment by divyakalraness** [comment]
![Credential Assignment](https://user-images.githubusercontent.com/104009274/165729935-2764cfa3-07f6-4d71-907e-a470c87156d3.png)

**Comment by divyakalraness** [comment]
![Cred Assignment](https://user-images.githubusercontent.com/104009274/165841935-1e5d2f1d-1f04-44a2-86c8-473f04949ec6.png)

**Comment by ghost** [comment]
I am working on second  AC:Given I am a Practice Manager I should be able to search the available Credentials and suggestions should be populated based on the letters typed in a search bar.

**Comment by maddiletiboyaness** [comment]
I have picked up the First AC to work   "Given I am a practice Manager when I go to my home screen, I should be able to search for Active Practice Members from the Assign User Section. "

**Comment by divyakalraness** [comment]
![Cred Assignment](https://user-images.githubusercontent.com/104009274/165977246-3cfe86d6-909e-4770-9a72-38b66a1f0c48.png)

**Comment by nitinsavanurness** [comment]
@divyakalraness  - can we assign multiple associates to a credential? or is it just 1:1?

**Comment by divyakalraness** [comment]
![Cred Assignment](https://user-images.githubusercontent.com/104009274/166121732-caad6247-3cd7-4ddb-8b9b-aa0353a2afe5.png)

**Comment by divyakalraness** [comment]
> @divyakalraness - can we assign multiple associates to a credential? or is it just 1:1?

@nitinsavanurness  Practice Manager can assign only 1 associate but he should have the ability to assign multiple credentials to him.

**Comment by divyakalraness** [comment]
![Cred Assignment](https://user-images.githubusercontent.com/104009274/166194830-9b6ee941-1cf6-4593-a426-8be1ede50cd0.png)

**Comment by maddiletiboyaness** [comment]
Working on LWC component, it's in progress. ETA is 5thMay.

**Comment by nitinsavanurness** [comment]
@Sudeepgangwarness - You can find the design [https://github.com/NessDigitalEngineering/salesforce-practice-studio/wiki/Design:-Credential-Assignment](here), this should unblock team to start development. Please let me know in case of any questions.

cc: @shilpijainNess  @divyakalraness

**Comment by maddiletiboyaness** [comment]
Working on JS, it's in progress.

**Comment by ghost** [comment]
i am just working on creating UI component

**Comment by divyakalraness** [comment]
![Cred assgnm](https://user-images.githubusercontent.com/104009274/173361029-4730e417-5cff-4f1b-b9ff-5980570aaf2d.png)

**Comment by divyakalraness** [comment]
Working as expected.
