### ISSUE TITLE
Credential Tracking

### ISSUE THREAD

**Issue by divyakalraness** [NessDigitalEngineering/salesforce-practice-studio#30]
As a practice member, on my home Screen I would like to see list of Credentials assigned to me so that I can Plan my learning. 

AC: Given I am a practice member , when I click on my home page, I should be able to see all my assigned credentials with the Credential Name and update Status.

**Comment by divyakalraness** [comment]
<img width="75" alt="Track Cred- Requirement 2" src="https://user-images.githubusercontent.com/104009274/164535171-4e923abb-42d1-4973-b36f-0a13e9441ba1.png">

**Comment by nitinsavanurness** [comment]
@Sudeepgangwarness  - The component should look like the below. 
![Credential Tracker Image](https://user-images.githubusercontent.com/102808229/165448576-9281046b-bc1c-4e25-8a40-9dec196a18ad.png)

**Comment by Sudeepgangwarness** [comment]
Sure @nitinsavanurness . @vidhyabalasubramaniamness this is the design for the
 component.

**Comment by Sudeepgangwarness** [comment]
Vidhya and I working on this issue. Vidhya is working on service and I'm working on LWC component. HTML is ready, I'm working on CSS and JS.

**Comment by vidhyabalasubramaniamness** [comment]
Created the getActiveUserCredentials method in a new Service Class.

**Comment by divyakalraness** [comment]
![Credential Tracking](https://user-images.githubusercontent.com/104009274/170670387-c923882c-8596-4b93-85d5-cc24fffd0635.png)

**Comment by shilpijainNess** [comment]
@lavanyayezzuness -7/27- To work on the spinner issue at my assignments and also aligned the text. 

<img width="956" alt="image" src="https://user-images.githubusercontent.com/104009274/181200861-6a969767-72d9-4157-b6b6-432b788f6dd4.png">

**Comment by shilpijainNess** [comment]
1/8-
@pathiputturniranjanbabuness -To check
 The spinner issue needs to be checked. 
Text needs to be adjusted

**Comment by divyakalraness** [comment]
Working as expected.
