### ISSUE TITLE
Credential Assignment-High Level Architecture

### ISSUE THREAD

**Issue by shilpijainNess** [NessDigitalEngineering/salesforce-practice-studio#31]
Update the design link https://github.com/NessDigitalEngineering/salesforce-practice-studio/wiki/Design:-Credential-Assignment-Draft

**Comment by nitinsavanurness** [comment]
This is complete. 

https://github.com/NessDigitalEngineering/salesforce-practice-studio/wiki/Design:-Credential-Assignment
