### ISSUE TITLE
Voucher Request

### ISSUE THREAD

**Issue by divyakalraness** [NessDigitalEngineering/salesforce-practice-studio#34]
As a practice member, on my home Screen I would like to confirm about the Voucher request for my assigned credentials and submit my Credential Exam Attempt Details. 

AC: Given I am a practice member , when I change the status from Preparing to Ready on "My Assignments" Section, I should be  presented with the  Confirmation question "Do you need a Voucher" ? which is default set to No. 

AC: Given I am a practice member , when I click on No on the confirmation screen, I should be presented with another screen asking to submit my Credential Attempt Details with the below information.

1. Credential Name - Should be auto Populated 
2. When are you planning for your exam? - Should be a Date Picker
4. Are you ready for your exam? Please share your comments.
5. Preparation Documents.

AC: Given I am a practice member , when I select the option  Yes, I should again be presented with the screen "Credential Attempt Details" , requesting to fill the information:

AC: Given I am a practice member , when I hover on Preparation Documents, I must get a help text "Please upload the course completion evidences from the respective official training sites".

AC: Given I am a practice member, I must provide Preparation Comment before Saving.

AC: Given I am a practice member ,on my Credential Exam Attempt Details screen I should also be able to see  "Save" and "Cancel" Button.

**Comment by divyakalraness** [comment]
![Uploading Voucher Request.png…]()

**Comment by divyakalraness** [comment]
![Voucher Request](https://user-images.githubusercontent.com/104009274/165493077-576eafdb-bc04-4427-ba00-4d23d04872cd.png)

**Comment by divyakalraness** [comment]
![Voucher Request](https://user-images.githubusercontent.com/104009274/165493521-e794faf0-77aa-4d2c-bab4-b7e26229abcc.png)

**Comment by divyakalraness** [comment]
![Voucher Request](https://user-images.githubusercontent.com/104009274/166658412-36252b04-61c6-4957-9292-aa38dab49372.png)

**Comment by divyakalraness** [comment]
![Voucher Request](https://user-images.githubusercontent.com/104009274/166971437-f321b08f-ec57-42ae-9797-8208e9fa8518.png)

**Comment by divyakalraness** [comment]
![Voucher Request](https://user-images.githubusercontent.com/104009274/166991006-19f2803b-fc4d-4b41-9c3d-fbe4e00ff666.png)

**Comment by divyakalraness** [comment]
![Credential Attempt](https://user-images.githubusercontent.com/104009274/182383170-5003a38c-a6bd-42ea-9252-603f0b6c126f.png)

**Comment by shilpijainNess** [comment]
1/8- To connect with Alok and confirm if this story is good to start

**Comment by nitinsavanurness** [comment]
[https://github.com/NessDigitalEngineering/salesforce-practice-studio/wiki/Design:-Voucher-Assignment](url) - Can get started with Service Class. 
@dipshikanalawadeness

**Comment by divyakalraness** [comment]
Working as expected.
