### ISSUE TITLE
Maintenance Exam Alerts - Email Alert

### ISSUE THREAD

**Issue by divyakalraness** [NessDigitalEngineering/salesforce-practice-studio#52]
Practice Members should receive email alerts for any upcoming maintenance exams which are due at a Periodic Interval.

AC: As a Practice Member I should receive an email 

Dear User,

Just a reminder, you have one or more credentials that require maintenance:

**"Credential Name(s)"**

**Take action today**
Complete your maintenance to keep your credential status by [Date and Time (local time)] or your credential(s) will expire.

-Team PBO

**Comment by shilpijainNess** [comment]
1/8- @divyakalraness -To check if this story is required.

**Comment by divyakalraness** [comment]
Not at a moment.
