### ISSUE TITLE
Credential Assignment- Email Notification

### ISSUE THREAD

**Issue by divyakalraness** [NessDigitalEngineering/salesforce-practice-studio#58]
As a practice Member, I should receive an email when Credential assigned to me.

AC:
Given I am a Practice Member, I should receive a below email:

Hello Practice Member, 
 
A new Salesforce credential has been assigned to you by Manager's Name

**Credential Name(s)
Expected Date of Completion** 

To find out more about this credential, please click on the learn more link.
Once you are ready to give the exam, you can request for an exam voucher from Practice Studio.

Thank you for your commitment to learning initiatives. We are rooting for you!

Regards,
Learning and Enablement Team
Learn More

**Comment by shilpijainNess** [comment]
1/8- @divyakalraness -To check if this story is required.

**Comment by divyakalraness** [comment]
Completed.
