### ISSUE TITLE
Credential Assignment - Select Credentials

### ISSUE THREAD

**Issue by divyakalraness** [NessDigitalEngineering/salesforce-practice-studio#60]
As a practice Manager, when I login to PBO, On my Home screen I should be able to Search for Available Credentials.

AC:
1. Given I am a practice Manager when I go to my home screen, I should be able to see " Select Credentials" Section.
2. Given I am a practice Manager when I go to my home screen, I should be able to search the available Credentials in Select Credentials Section.
3. Given I am a practice Manager, I should be able to select multiple Credentials in Select Credentials Section.
4. Given I am a practice Manager, If I started typing in search bar, I should be able to see the matching results for available Credentials.
5. Given I am a practice Manager, my search results should be refined every time I type in a character.
6. Given I am a Practice Manager my search results should only show those credentials that are not earned by the Practice Member in the past.

**Comment by divyakalraness** [comment]
![Select Credentials](https://user-images.githubusercontent.com/104009274/167829881-c8d686ee-c791-47a0-a08f-e59270631a6f.png)

**Comment by shilpijainNess** [comment]
1/8- Unselect the user, search results are still populating @maddiletiboyaness -To check

**Comment by divyakalraness** [comment]
Working as expected.
