### ISSUE TITLE
Credential Assignment - List of Assignments

### ISSUE THREAD

**Issue by divyakalraness** [NessDigitalEngineering/salesforce-practice-studio#61]
As a practice Manager, when I login to PBO, On my Home screen I should be able see the List of Assignment (table) with the below fields.
Credential Name,
Assigned Date,
Due Date,
Status

AC:

1. As a Practice Manager, I should be able to view the credentials which are already assigned to my selected team member in the table with their respective Due Date.
2. As a practice Manager, I should be able to see the newly Assigned credential in a row.
3. As a Practice Manager, I should have the ability to sort the Due Date as needed.
4. As a Practice Manager, I should have the ability to modify the Due Date for the newly assigned credentials as needed.
5. As a Practice Manager, I should be able to only delete the newly assigned credentials.
6. As a Practice Manager, I should See the Save button.
7. As a Practice Manager, on click of Save, the Credential should be assigned to the Practice Member.

**Comment by divyakalraness** [comment]
![List of Assignments](https://user-images.githubusercontent.com/104009274/170668162-89865623-6ade-47cd-9939-fca4e0941091.png)

**Comment by shilpijainNess** [comment]
8/1-
1)  Due date manual is not working @maddiletiboyaness -To check
2) Overlapping with assigned date field

**Comment by divyakalraness** [comment]
Working as expected.
