### ISSUE TITLE
Credential Assignment- Earned Credentials

### ISSUE THREAD

**Issue by divyakalraness** [NessDigitalEngineering/salesforce-practice-studio#62]
As a practice Manager, when I login to PBO, On my Home screen I should be able see Earned Credentials.

AC:

1. Given I am a Practice Manager I should also be able to see the Earned Credentials section.
2. Given I am a Practice Manager I should be able to view the Earned Credentials if any for the Selected Practice Member.

**Comment by divyakalraness** [comment]
![Earned Credentials](https://user-images.githubusercontent.com/104009274/167113407-39af6fb1-a3d5-4044-ad05-4f46a7288a84.png)

**Comment by shilpijainNess** [comment]
7/27- Pending Updates
1) CSS changes
2) Icon not visible
3) Scroll bar is not visible
 @vidhyabalasubramaniamness -Check on the data load if that is correctly done

**Comment by shilpijainNess** [comment]
@vidhyabalasubramaniamness -To check on the "show more". Take the latest code and update the same

**Comment by divyakalraness** [comment]
Working as expected.
